### ISSUE TITLE
Camera stops working after a while

### ISSUE THREAD

**Issue by dietervandoren** [diablodale/dp.kinect2#7] opened 2015-02-07 16:26 UTC
Windows 8.1 Pro 64bit updates applied
Max 701 32bit registered
Kinect SDK v2.0_1409 (Kinect SDK v1.8 also installed)

Gigabyte GA-Z87X-OC
i5-4690K (no overclock applied)
Corsair 8GB 1600MHz
GTX670 graphics
MOTU Ultralite mk3 hybrid (connected by firewire)
Dawicontrol DC-FW800 PCIe firewire card
Sitecom N300 USB wifi dongle
Sparkfun (FTDI) USB Xbee receiver

I 've had 3 times today that I left my perfor;ance patches running while doing other stuff (not on that computer) and when I come back the kinect 2 has stopped working. The lights are off and dp.kinect2 doesn't output anymore. No error messages in the Max window.

When I send 'close' and 'open' to dp.kinect2 to re-establish connection I get in the Max window:

kinect1: close 1
dp.kinect2: Operation aborted. hr=0x80004004
kinect1: open 0

It won't reconnect before closing the patch, which crashes Max entirely, and re-opening.

The kinect patch is copy-compressed below. It is part of a larger setup comprised of dozens of other patches and dependencies. Can't send all of that. I'm currently testing whether the issue occurs when only the kinect patch runs.

<pre><code>
----------begin_max5_patcher----------
6570.3oc6cszaiqjcdcO.y+ABmF2EC7UtdWEmEA8LSxhY0M.CR1by.CZIZad
aYREIp9wLH42dpGjRjxTEOxsJRJa2Fsj36S8wScdUm5T+ye+u6CWcWw2R2bU
zeL5Wi9vG9m587A69L64C063CW8Tx2luLYi8DuJO8qE28aWcc0wJS+Voc+qh
9ZV9tcmu8or7kok1qAWu26KxKySdJ0dA+o0YIKadAEaKquBT8tyVXOW8S7mE
7cm7pjx4Olk+vsqSmW5H+XJZF55HpPMiq+J1rAgLCE82a9vuOYdZq6uYmax9
G1ch0md892T98kNxr8CMccE1TCN5aQ1xzujtdSVQdyF6GtJY0pF6+CMuHCl9
aE16k7586KK2sOz98sN8KYO6Vqu2q0.Pot0ucsiL+lRbUi6Twhz04ayrWU0d
+e+8+tcj1dbiYZzQXgEvvbJ17shiafbZVhGVVL+yoKZQaWUrJMOKe05zMo4k
IkUD49iuH89jsKKu8HXb6S3v2LsOZ2LMe3pGVmsnH2PHsgdy9qej+ptY4Zbs
ZS1SIOYUWWtlcSCPG6nazM1satKYs4MycN1DxtiVVTrr8w1ekKSuur53qxxy
ODPKKV44nqyd3QeW8cE5i9j2au8Patcat6v2p6TWd6ljub.xWlrbYU27CdBe
KIO6ojxzxL26CBZ+QSySzM3G2Lecwxksa2tC8ktNzBM+87zulsn7Q6CqE6g9
BxVUyXc09W6KxdHcS4A6rL4gMGrqm2KVuus2U0S91xzmVsT2ZN3LZITrUu1l
BGaefCDRZk8su+3gBDQGbjFR9vMOTCoe3V2sND.hkVlb6mUxBQMY3s701mS4
2WU0w3peKq7V86y0Y5VUqyrCjyr64EO8jtyt6.61uVxR8uMBYdwnllZlsRqE
YQwWON10BfZJ7oAVXa91OHXmfMA+PrnMrSNBryP8g6BxdbGiDrYLIQJUZgnH
Ru3+UWq+eze+HHYCoUKyxOJOoknLmvQv3MEaWOu9IVwKEc.ko6qUlkuSH9ut
u0e3Y9X1hEo4OiKdQ1FSebmHmi1dbarWSzUFgOKt0Iu81jRMm3caKcszVJYO
QYAZ8U2krrpe9NkG9ELrW9wNpz9ipuq3rgYjzVcujs8XLTaFPZGV7DS7YwCF
wDFlNtx9okAjPaZwyyX2xzccudGW2968ZMBUpEH5jSebCjn6MPRa7wSULjW8
K2eu4Vds4ieIuwctAL+hgRM+PYQ9Igk3tvRLDrzYo.AU+oGr7tj7GNyM0iYZ
cxBmIGQa9Zllz6FKHmrQ1jNfIULDXhZ+Ll9bir6TBmgsqsc38Xx8KFAKKd3A
8M4GkYQo75pAuAH.hWoM.3s+VH4iVVjr3ozMahPmK+z5B7DL.fmqilj.gCZX
XcNFnsHY9+24pGWmt0h..WNY7TY2d0NzPxpn4IKyt61ujk90P5wO2a2PhrxJ
WqKqRwKBadc6bOwZ7K2hSXJlYkZaPp28s+ce6e229WlWpFMnIOj1xuvchFML
l5NBJTTr.cbmXa4tomNAviOfpO+TcRK4tv6Y6yn528z1G+Xc16Rey4Lt.8i3
BZ7PC3x9.bhfsCwkwu1PbKONSFOjPtn2Xf4Bi8EIS9pj7z1fxWR1G5hrhe1d
B+Z7eGXnwtqX8BmAM3iizniwbS6MrWVaubw9RyJX9lY3xaClNhXdwRmoOUQl
C27i1Wv5hs4KNP4lm3QZLE5Ymq1w7JmpZ+16tGZPH31DxyBU5p0EqJVuyvmY
z3w5MtZPdiKhOg23B23qok399K7wM9108853UAr.bSdAcz63gchQ195KoQVw
h.Vc4Dd8miv3pDpQCPAcz.Hm0AC35y.oKgR5FoaSLZW.k1M5hmXzNdbXYd6L
9QGKxaZskkoZDE2cX2nmbX25ZXm3Regci4bkwIJzEWR.CAvAC4THiZYsrzmA
dnnGSSVD8emiixSm+Y8OHQkEq2Tn+EMZ8sadrX6Rs0K5MYQKatIWezzk2U7U
8uE5CU+aod+OljatmJ8tq9YrYuYqLOHjYuteh068y4ooleSz6t92lm78EEkl
eadrleui1McJmqsPx1.v7.FqUlv6KcsAeb8acLhZ+FIMeQvzgJTzG8k5+4e6
OGYraK5eIjQhlQ8gNRgblzfGMFSCzPgLG3p9djgdtF0hNGjGuiSnByc.Bq1G
7ywn7XZYG5YQCKgad66HB+28v8YKWZu9aqetW8v5jEYM4qZdV1OwG58vyeXO
6ZH0DnPwu9fu7ek0WHIFgiElKhhhUHl6W5cg8bG14FjajQ53LdtONcde1VVr
CXrmmL97ydRBI6oz6fpIisuIem67ctyiwchCJ2Iwu1jVBOsJdem87MI6oe2.
vQjninjmcx7ort3S494ScYAjMoDDmji.Cmy.5F4coqavg1YDAeNa4OnMjckZ
URFjd8tAqm4TPI6ENOHKz7lZQZmia0OQZ6Xs+S7QMYUr+kxiGdWTRy0qHlOI
rCtKuLoNm89KeI5yY4zPlzSRuNHnXN2lbYLG6BHqmrHFInHl.BhI3WTHFNnH
lBBhQmbH1gFYEBKp7m1pXVU54yqLoZxhMMiqw+0e8e6VDCE+S+Glef3+I4Oo
e6FGKk3eB8SrPhmJuYKsRob3nKAfkpKW7j8WDh+8+rL33IEBd5D1cYfmUYv2
mMAnrT2RCI3wg.dzoG3cz7mcc5pz7EQYKbvWHUZn5QMqabMc9ZFGO8wts4qR
l+4nMl+NW3VWCBhRB.2b99HkWPCBxFCi2phr7x4KK1tHnSXaurdwUtLVM+43
ngMr4Gi+ZypzzEKydRar.JjB0nwPlM6DK3nt.L+8ASt1FR7xqEIDm+xt35Jj
SG35LMgjXb.sdA4RaBIYRHp4Olj+P5UALvKTuCF.U61DR+OkYPscc6DP5u0H
EetdxXQwlzfZLAO1+DxQMih3BgIJPHmwDR1zWzUYzcAEz722kRlEi0XFVaNg
K85HPvrCB72qQbyq4C3X163V23lWeMwbrILQuCYsfLl+vGsWEw63VKby+.Yh
eG15F1v.MH4BC1VsNKuLnogkBpJAL1kGVT1vNkoMof51rWNFXt9JG3yMgFJc
wIvWw7WuPnh8vSkkt0tcOosOy3kPdZ4LanK9T1J8CV6gm9Obzmro9mDKCpu5
LLXGHpBpAldADBWdP8WW.0pWLBiqliI7IOlEzQIfBW71kDlEzDQkBwZ2KJ3J
nIFIkC0R2KJLKnoqGEpUtSQHyiItQYgLpajXnJMQTEXTyZk6fVRoNJOWPM4f
HAidWN7bqR9rIBkySWtLJS+2WRVFcu6utwR04AK4PwRbqI2zDWlWMR9QbDxB
kejG8QRzGoQeLnVofED3QAVV4lwDZHYN5PitN0N40+iQZeutOaQZ97znuE88
n+QHcoEKnPl3UHQUJhPmFCS58a0tmtT+h8HXC+Lwpwfyp4zhH37YbJkR5WZ3
xrMkirDwe4u8W9YWxbeictIdichIdiaVIdSioj3MMlOh2TOYDuodlHdS0zP7
lp4f3MtIf3MtIe3MUS7vaplzg2TMgCu4fIa3OZjtDcI6kB+EnSQlzUO2NkTI
+T++3GNC2.GFwhteYQRIkn6vDIBp0XvCgAptbwMUGDziJ.e6lz02r4yoZZrH
WCslIjc.EcS7NtxBhMebUUUFZ2Wiuf6PmmFPRqERr09JpZxlmFslmHnSddh.
PyFBBNIdokX14OlZpoi.m5Edy+is48dyPC073ng5x+PPkV5e1iNSP0+YR7O1
9h6FDEViuK+2ERXCCHGsjbmUZPGQqqGzQ15rM7MYqNk.L40JWUrVQBWFqnZs
IJYi70ch6OUsl3vpD1e8SlhswEodfYj3ogV3.O.yD+CLeCy8TUqTRWHivbCE
.3naHQ2PitgEcCO5lyl0yxNwS+yuHM7Y.TLeGfRAkCgSTOTpylPbjwh5Pxnh
E8jbbxYLFAQI6T1Fiu.leGIe1Feyp+5F.EmG.z+LKpE.x1GBIhL1z6+xXZxf
iLZRBJanxqFXNhXQQrzTm4snnJ9c1vV.HGL.VuhyM0XC60NlvFKAuZXDZtNl
HVwhM1vPc0f0IRcl5i3nfN7qDhWiYXRp0eLN03VA5XI80ja3aLCaSXgMuZF3
X1TF1N9zyZcx2ijA0XOBCL+laUGAqMJQQoTIapaw2YZ5HQ7mcWBr7PoUSwYk
zYCL7NV8Bl3MEX3MG13lJGMmhQ32FfgWk5bkZlhqjB9aBvf4MPMlUdXBSxnx
2FfAFr8xSWvv6.wETqk8mo6LDsgHWYiwZ5Mf0x9KUsDjxM5Ep2sVtMr4OSSX
wSYXaLsVtmoldS9M2rY5sm0x9qs1TNYlPvnH4NoUup074OyVU3CEc+pFL7uB
WZxShcVK+5GL7mw3DZCqke0CFbuVKaxLj8VK+5GLvfGjioKXbzJZ0hU1Y139
Y0nDywAcZz5OVyXWQGxMPlXVGyPzVoBDlwQwJaV.IYbrsZKKELI1WEkcnra7
mC5jOif8GsCo00MNcpMAMNpia1BCVTvqLXDjWi.hcoJTrbRkyFaLIqqollGT
fw+BWfKEo0xC2utNO9KG3.le17f57FV4e0HwMhiwNT6jma1GVwvQctXF95sp
Bfi8W+MEMROMhXxUUANaX2iEaJOIXyeEjTQ1Cab5jKq9NavlQBvIAadUoFii
mo8T1BawUoV+jpFVzd8FHDIYar.fMGNUmvPlSbYDXTriKcY5WrKtfQeLngOE
Gy.ftUERbI+xoVCGzJSON1+5ilrR9FEbtee0jvVufNwOiIPvLmQKL5zvTOWt
25AaHmEYb9SGuJnAGCepDLARp1kEIKbyngP1ODAnpUic3F58Zwl02A+oxhaY
NkSlhYI+xF1wevLVSQpiEyy+EfIv1QV2wcngBEuOADEzCtacg22sLK+ykYtW
QbTmhC8Wv0qdOnXG6I2jha8r6IreE4.moedsIp396acaDwLL1FSrm+qAaUOZ
WoLmiBr62J.u5b0TiKgRYdvmmbB.yStpECDQ7zbhx4sDPF4VVKBZjxvTHKPC
b9QMTeTbiwjXLlB1xfTmV5IU7LKdEwHkBuStJFgu.REj0oZ47VXLrnm2XJJQ
plJjtDpWPoeKqrh+Kn.m+77SPoM5XJtDVJtlmrL6t0tnObWxhfied0NvTzYX
LFoXM51xuvPwGJJBOLBdViTwKhwjKIXL+gfifdCpCUq+PQoLyJsaEin5R..2
TtN6yoQIQqJ1jFbHj4OkVhaHKL9RnW7eMZYwlxfCa9yoPWQkqB13zKBXaSZ3
Y17WxkwSUTa78kveNIVgbhlEvjwOTrMJEBlInpozw80as12cioKZ0OspKt0J
pq52aJSVWtaisymq4Yq279jL8MxckFyEqtIUVbWs0YMx33NGhqdpy+shnfHV
ctqWbirvhGR01oeW1Ba8ILjk0d.NP6VHxkmI+BeYKG36Cw48YKWZu9aqetW8
v5jEYMykolmk8Sb+w16YWCYWf7T1kG8le4+JquPRLBaLMBMihhUHl6W5cg8b
GRxev0ncp353LVstvLf5UA4TeKi679rsrXGvXOOYbPR6mhUQeR++ah9jo.zx
B5XB0i87tpfLVA2T9Qo3EZPsUeMKeQwWu5EEC988WHtExZq3viEB9NQRDDjj
oN9y3XiuVH4w9CNdLBmGRtLozeTeZwkQjuykc7fb6epMnUuvGZtL.YWxOiC6
phROCxkCFbCPq7BnDy3L.8rasRmqhm.rVop17bgjQ.Cl+M9mKIhXRizoXp3d
SCI++qNI+nPxcwfH2uZ8EFiEuK2+3HIBhFzAUt+YDUnUyrHF5zPE+0TFxzzj
qJy5UyBYOO+U2IRay5mrc7.XZQXsr.yfXYAcxk2p..tvl7JB.3VL5xYvJWVr
InE3cr2Xy6V.cpDgQieOrQuYCazQ4PKVklG1L2neFzJicox2YPemAsi3uuS4
SPYTIPlpIWPpr0.2YcpAzEnAYBWWO.Q32RyKLo+kQLaUvmer4RxjdRgcLOU9
ezTy5hHZPmh+h98NgchKoEuNWQa7ZVnUOqSkKp9y25KlMKVMyE6ORzCKWjtp
7wnOY+5oDSXHhv62LhD8IC7ra4B6SV52bDTzmpqO02a1So45VsL46oGdXyAR
Vl8f8GKx1TZQIyFGbCzWy5hxjxT8I7XwBy1VBYsl4MMZuRqkFpuXqSULIf0X
Lr+0rXbCK5vHW.ZnhSHFAuzs5H9B2mLe3DLd1li107YmhwKd02fcChnSgCAI
eENu1azU8jlgd.fMmBEbr50JrUju76NYTmB1QD.vNmgxuNq.EVo2mBfo7m.u
7W6.1d0VmzzYC.pU4V1qSXam4CmRxjwfnO.8JF0pMI6TbtfBgUyoDE+ZDytq
Xw2Mg94TvLPFdTUcdcVdXRNfeLPqXcVmSt3IIC3oYQh+Uy8JdvJKRjuFsHoo
uNm.tIwP56NXB7bWq0mrMt62NfzRdlCb.btoX6540Ob6Z2qlUHpAEtHcSYV9
Nt9pyxTr0ZdVOlsXQZdKmddJagsRBVQIZTf6VKjcXB0UfIasEstv5XOSZq41
u1YUim7VrGcbFF3sS7Ypcd1ILHzEc3oKEHB6P1mgfvTPHLyRD5PSXRPrXb8Y
gGdBC2KgQGGBizKggGGBq2WkR03vi06qRoXbHrdeUJoCOgIf7pDep52L0uQS
s80UkfTUUL4Vagcq8ABpnisbqUr0SC4C1pJUyQ1AvwrU3zKZEG0uPqQfghAg
vrEO2IIkYqOdCMkAyXtQ.xBRePtxsPeqnM6unBpcjx3yjR9CsWFyEtUsbk8q
laN5sF5Kt0TMHzM2bzaM3WbqgKa0ZLaFvViZhJYVBx3H1vKkQJlpHFehZNoj
OQMmzRXSQyIkfT9e3K7gfvnSUlePFkbHt1uTYojOinECyrBkatU.kIiChgLL
DyorW3BKVk8Ls1pZgTq1HGTPMxAElWYJjk5Gz2XfBVzfGfAQbfPXxv2oPHCR
mBCONefY7EfjtqFdE0BZHE73hIA0Ec9VaLrnOIjMRQy1kX7ZjfTgP3jSsYRs
Te0zvQzXJ4Hb0oMRch.a9mpZOAtch+weYd1oKP7XCOcwigwWL7DFLw6iDg0O
G1v6i.GDOFc30hvA4GJc38QfCRuKcD3w.o2kNB7XfzURG9gmkCS+lb3ILndB
LAIK9vCWLXCA5HPXvDhM7ZvYrf5GT05rGY+Vgy3MFHoKrQ.iAwTFOMoqW5fL
KItEuGKCPGaTuhGzZPjGReZnfrcEOBYWEEzfnPFABKLAMQHbCenKU0EtpKyg
a0hOgNdbMho56F9TkvXS19YzoJjQlpDFL6jGdC3onIpteXCv0vaPpk4ACJxM
jgkvTgLdpwMGdp3QarpHxIZGbhHjtCD2zaf3f5L.wFZR1DLdVNJiOACnkixH
SvHZ4nL5DLjVNJCOAioEAXv4kSVJax91bznLxjkxnSVJiMYoL9jjxf46woa.
ViAwM1sbv4JB1M2.WYEViSFGZSwfE6erZLdWffSZ3Alz.4u0oYcEdvHLxv6H
HgEC+kIcfIMEbRaf8FD1H53HM9.SZB3jFafIMNLu6GitAfRR5mI5avHs9MWf
EORjV+1XwTiDoI5mzjiDo0uUVLwIm1ZBxLrfgMkiVoaMbpZWTjrZWAzjEXCZ
KgMBNpynSWRCngdiAogfSZCrgdPGlT9va1BUAmzFXyV.NRoJ9va1BU.mzFXy
Vfku3B1v2AkBJqMsTFd3oLBLJiL7TFEFkQGdJiAixFgd.bXTFe3oLALJSL7T
lDFkIGdJSAixTCOkECixhGAIs.UBfGCs.PUCLB5Av.UDfGAMAXfpBvift.LP
kA3AVa.gAJLNiPZs3Hs9CiyHTPEbjFfQ8IdjHM.CUlZjHs9CiCUNRjFfAK6j
CiifH2GFGjcDnDDwrXQrhEWsq.FFGX963Z9CMjSltjFnoDCehRXiAhggEmj3
QHii.ERN5vqDAGqlpYsLNVNcIMXwVJlMBjFe5hZrfVo4HzlSVh1aMjI85yJt
fGi6fLBuBfk+3i.gEx7wUzLebEAMebwJfBTGdkPXfUa0QHK8wJfRsFANSXUT
T1IWD14X7rXFAgkWGoPthABAaKK6lsBIKJvwefOBfcPKgWCpVffV3knMknQC
qDMAOLc.HLgsC.kLzc.fUIovhQPAMrxrDeDrdSDz4DaUTIplErs2ZxXXGOP1
uZqMTLZild6szlJ1rUFGzrtACKKIIiAOnkz.DMV1HQZpoKoAH75zQhzhmtjV
+7ZD5jkWazHs9ig8HL0ogJWavSkeLzzRWMUEcfYhoZ+S7HjAlNRq+wAdzzEz
+v.ylrhNvrwRzQ+YEzHL.0.0EfGgAnFnxcLcrLjr+johNZhbAT5LGgvzAbp.
AXNPbXr.vw1Xyhv00F25sBoiN7P0ZjiQqgEnVCkpFgVCMPsFFRNiRorXgtQf
40kkYd0VgrIQBUSRQmgoBJmN3ukvgpIESlIvXjhM3ukPApIIXjQnaTPCZGuU
n33iWf4.N4cN8WZRrbGS2fwBRCYXFwMJITs1XXCxHInoBvjgwDj7QwH31.Ho
bifg4P7NM9TWi3jJ4LkVoOldscTmrK4BUwYu0Vb6WwUcU3AMsHwPboTcxKxL
XraLzHTqdFI2NvZGrE1UfZcqkos2pRLfrpmTfEC.ZIFlLJrg85AlPMMoK93P
W8xKCnTG3mWVn6FiNbqZ9UDdf3W6MtdiPE..Ctpqimd7EzeX1BVK1BWcVRX0
1qbV3zdKg8yp52sfFZFF.gz7GqGq6BuJY0pujtdS081QSW8TxuUr1rs7Z21Y
4tsc24qVm9kr5KA61Ux54OlUlNub6ZaS4puYRbL2UWrHcc91r5g9vRC5O9+Q
oBGqX
-----------end_max5_patcher-----------
</code></pre>

**Comment by dietervandoren** [comment] 2015-02-07 17:52
It doesn't seem to hang when only the kinect patch runs. I'm trying to find which other patch causes it, starting with the ones that receive the 2 jit.net.send's matrices and udpsend's message.

**Comment by diablodale** [comment] 2015-02-08 10:30
OK. When you have a repro, please do send it my way and I will try to reproduce and then isolate it.
You might want to test additional things
1) Run Microsoft Kinect Configuration Verifier at http://www.microsoft.com/en-us/kinectforwindows/purchase/sensor_setup.aspx
2) Run one of the Microsoft supplied Kinect samples and run it on teh same machine for the same time and manner in which you are having the problem.

**Comment by dietervandoren** [comment] 2015-02-09 10:55
It seems to be a Max issue, not dp.kinect2. My Kinect patch exported as stand-alone keeps running steady while the other patches in Max hang. The previeously stated symptoms of dp.kinect2 malfunctioning appears to be consequences of something else hanging Max, not the other way around.

**Comment by diablodale** [comment] 2015-02-09 12:47
Got it. I'm closing this issue for now. If you isolate a repro case in which dp.kinect2 is failing, please re-open this issue or open a new issue for it.

Perhaps as a help... There is a block of dp.kinect2 code when you "open" the Kinect that can return a 0x80004004 error. Such an error is likely due to:
1) a problem in Max which forbids me from successfully allocating memory structures
2) a problem in the Kinect runtime/drivers which forbids me from successfully querying for camera alignment information

**Closed by diablodale** 2015-02-09 12:47 UTC
Labels: invalid
